name: CI
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        platform: [windows-2022]
    runs-on: ${{ matrix.platform }}
    env:
      CMAKE_PRESET: windows-release
    steps:
      - name: Checkout Current Branch
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Run vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
      - name: Run CMake
        uses: lukka/run-cmake@v10.5
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          configurePreset: '${{ env.CMAKE_PRESET }}'
          buildPreset: '${{ env.CMAKE_PRESET }}'
          packagePreset: '${{ env.CMAKE_PRESET }}'
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dcmtk
          path: build/windows-release/dcmtk-3.6.8-win64.zip
          if-no-files-found: error
